"""Reusable agent modules — the `torch.nn` library of operad.

The package is organized by *domain*: each subfolder
(``reasoning/``, ``coding/``, ``conversational/``, ``memory/``,
``safeguard/``, ``retrieval/``) groups its leaf components under
``components/`` and its composed multi-agent patterns at the domain
root. Structural operators (``Pipeline``, ``Parallel``) live here at
the top level because they are domain-agnostic.
"""

from __future__ import annotations

from . import safeguard  # noqa: F401
from .debate import (
    Critique,
    DebateContext,
    DebateCritic,
    DebateRecord,
    DebateTurn,
    Proposal,
    Proposer,
    Synthesizer,
)
from .coding import (
    CodeReviewer,
    ContextOptimizer,
    DiffChunk,
    DiffSummarizer,
    PRDiff,
    PRReviewer,
    PRSummary,
    ReviewComment,
    ReviewReport,
)
from .conversational import (
    ConversationTitler,
    ConversationTitlerInput,
    ConversationTitlerOutput,
    InteractionTitler,
    InteractionTitlerInput,
    InteractionTitlerOutput,
    TextResponse,
)
from .conversational import Talker as ConversationalTalker
from .conversational import TalkerInput as ConversationalTalkerInput
from .memory import (
    BeliefItem,
    BeliefOp,
    BeliefOperation,
    Beliefs,
    BeliefsInput,
    BeliefsOutput,
    MemoryStore,
    SessionItem,
    SessionOp,
    SessionOperation,
    SessionTarget,
    User,
    UserInput,
    UserOutput,
)
from .parallel import Parallel
from .pipeline import Pipeline
from .reasoning import (
    Action,
    Actor,
    Answer,
    DebateAgent,
    ChatReasoner,
    ChatReasonerInput,
    ChatReasonerOutput,
    ChatRoute,
    Choice,
    Classifier,
    Critic,
    Evaluator,
    Extractor,
    Hit,
    Hits,
    Observation,
    Planner,
    Query,
    ReAct,
    Reasoner,
    Reflection,
    ReflectionInput,
    Reflector,
    Retriever,
    RouteInput,
    Router,
    Switch,
    Task,
    Thought,
    Tool,
    ToolCall,
    ToolResult,
    ToolUser,
    VerifierAgent,
)
from .retrieval import (
    CitationGist,
    CitationGistInput,
    ClaimItem,
    EvidencePlanner,
    EvidencePlannerInput,
    EvidencePlannerOutput,
    FactFilter,
    FactFilterInput,
    FactFilterOutput,
    GistBatchOutput,
    GistBlock,
    GistItem,
)
from .safeguard import (
    Context,
    ContextInput,
    ContextOutput,
    SafeguardCategory,
    SafetyGuard,
)
from .safeguard import Talker as SafeguardTalker
from .safeguard import TalkerInput as SafeguardTalkerInput

__all__ = [
    "Action",
    "Actor",
    "Answer",
    "BeliefItem",
    "BeliefOp",
    "BeliefOperation",
    "Beliefs",
    "BeliefsInput",
    "BeliefsOutput",
    "ChatReasoner",
    "ChatReasonerInput",
    "ChatReasonerOutput",
    "ChatRoute",
    "Choice",
    "CitationGist",
    "CitationGistInput",
    "ClaimItem",
    "Classifier",
    "CodeReviewer",
    "Context",
    "ContextInput",
    "ContextOptimizer",
    "ContextOutput",
    "ConversationTitler",
    "ConversationTitlerInput",
    "ConversationTitlerOutput",
    "ConversationalTalker",
    "ConversationalTalkerInput",
    "Critic",
    "Critique",
    "DebateContext",
    "DebateCritic",
    "DebateRecord",
    "DebateTurn",
    "DiffChunk",
    "DiffSummarizer",
    "Evaluator",
    "EvidencePlanner",
    "EvidencePlannerInput",
    "EvidencePlannerOutput",
    "Extractor",
    "FactFilter",
    "FactFilterInput",
    "FactFilterOutput",
    "GistBatchOutput",
    "GistBlock",
    "GistItem",
    "Hit",
    "Hits",
    "InteractionTitler",
    "InteractionTitlerInput",
    "InteractionTitlerOutput",
    "MemoryStore",
    "Observation",
    "PRDiff",
    "PRReviewer",
    "PRSummary",
    "Parallel",
    "Pipeline",
    "Planner",
    "Proposal",
    "Proposer",
    "Query",
    "ReAct",
    "Reasoner",
    "DebateAgent",
    "VerifierAgent",
    "Reflection",
    "ReflectionInput",
    "Reflector",
    "Retriever",
    "ReviewComment",
    "ReviewReport",
    "RouteInput",
    "Router",
    "SafeguardCategory",
    "SafeguardTalker",
    "SafetyGuard",
    "SafeguardTalkerInput",
    "SessionItem",
    "SessionOp",
    "SessionOperation",
    "SessionTarget",
    "Switch",
    "Synthesizer",
    "Task",
    "TextResponse",
    "Thought",
    "Tool",
    "ToolCall",
    "ToolResult",
    "ToolUser",
    "User",
    "UserInput",
    "UserOutput",
]
