"""Example 1 — compositional research workflow with reusable agent primitives.

This script demonstrates workflow design + invocation primitives on one agent tree:
- `Sequential`, `Parallel`, and nested composites for orchestration.
- `abuild()` to compile and type-check all handoffs before runtime calls.
- `validate()` to check request shape against the built contract.
- `hash_content` for prompt/config identity tracking.
- `__rich__()` via `Console.print(agent)` plus `summary()` fallback.
- Graph introspection via `graph_outline()`, `graph_mermaid()`, and `graph_json()`.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from functools import partial

from pydantic import BaseModel, Field

from operad import Configuration, Sequential
from operad.agents import Parallel, Planner, ReAct, Reasoner
from operad.agents.reasoning.schemas import Answer, Task
from operad.core.config import Resilience, Sampling

from _config import local_config, server_reachable
from utils import (
    attach_dashboard,
    parse_dashboard_target,
    print_panel,
    print_rule,
    rich_available,
)

try:
    from rich.console import Console
    from rich.tree import Tree

    _RICH = rich_available()
except ImportError:
    _RICH = False


_SCRIPT = "01_composition_research_analyst"
DEFAULT_DASHBOARD = "127.0.0.1:7860"


# ---------------------------------------------------------------------------
# Domain schemas.
# ---------------------------------------------------------------------------


class ResearchRequest(BaseModel):
    question: str = Field(description="The research question to answer.")
    audience: str = Field(
        default="a curious general reader",
        description="Audience profile for tone and depth.",
    )


class ResearchPlan(BaseModel):
    biology_question: str = Field(description="Sub-question for biology.")
    policy_question: str = Field(description="Sub-question for policy.")
    economic_question: str = Field(description="Sub-question for economics.")


class BranchView(BaseModel):
    perspective: str = Field(description="Perspective label: biology | policy | economic")
    sub_question: str = Field(description="Sub-question investigated by this branch.")
    reasoning: str = Field(description="Reasoning generated by the branch.")
    answer: str = Field(description="Committed branch answer.")


class _PerspectiveBundle(BaseModel):
    biology: BranchView = Field(description="Biology branch output.")
    policy: BranchView = Field(description="Policy branch output.")
    economic: BranchView = Field(description="Economic branch output.")


class ResearchReport(BaseModel):
    headline: str = Field(description="One-sentence final stance.")
    reasoning: str = Field(description="Why the stance is justified.")


_PerspectiveBundle.model_rebuild()


# ---------------------------------------------------------------------------
# Composite assembly.
# ---------------------------------------------------------------------------


def _combine(views: dict[str, BaseModel]) -> _PerspectiveBundle:
    return _PerspectiveBundle(
        biology=views["biology"],  # type: ignore[arg-type]
        policy=views["policy"],  # type: ignore[arg-type]
        economic=views["economic"],  # type: ignore[arg-type]
    )


def assemble(*, cfg: Configuration) -> Sequential:
    planner = Planner(
        config=cfg,
        input=ResearchRequest,
        output=ResearchPlan,
        role=(
            "You decompose a research question into three independent "
            "sub-questions: biology, policy, and economic."
        ),
        task=(
            "Read the request and produce one focused sub-question per "
            "perspective."
        ),
        rules=(
            "Use the same language as the request.",
            "Each sub-question must be answerable independently.",
            "Avoid copying the original question verbatim.",
        ),
    )

    # Reusable constructors: same role/task/rules, different per-branch context.
    ResearchFramer = partial(
        Reasoner,
        config=cfg,
        input=ResearchPlan,
        output=Task,
        role="You frame one perspective-specific research task.",
        task=(
            "Use the context to select the right sub-question from ResearchPlan. "
            "Set `goal` to that sub-question and set `context` to the perspective "
            "notes from the static context."
        ),
        rules=(
            "`goal` must come directly from the selected sub-question.",
            "`context` must stay perspective-specific and concise.",
        ),
    )
    BranchSynthesizer = partial(
        Reasoner,
        config=cfg,
        input=Answer,
        output=BranchView,
        role="You package one branch result into BranchView.",
        task=(
            "Set `perspective` and `sub_question` using the perspective context. "
            "Copy `reasoning` and `answer` from Answer without shortening."
        ),
        rules=(
            "Preserve `reasoning` and `answer` exactly as provided.",
            "`perspective` must match the branch context.",
        ),
    )

    context_biology = (
        "Perspective: biology. Use `biology_question` from the plan. "
        "Focus on mechanisms and empirical uncertainty."
    )
    context_policy = (
        "Perspective: policy. Use `policy_question` from the plan. "
        "Focus on regulation, governance, and incentives."
    )
    context_economic = (
        "Perspective: economic. Use `economic_question` from the plan. "
        "Focus on costs, market dynamics, and tradeoffs."
    )

    branches = {
        "biology": Sequential(
            ResearchFramer(context=context_biology),
            ReAct(config=cfg, context=context_biology),
            BranchSynthesizer(context=context_biology),
            input=ResearchPlan,
            output=BranchView,
            name="biology_branch",
        ),
        "policy": Sequential(
            ResearchFramer(context=context_policy),
            ReAct(config=cfg, context=context_policy),
            BranchSynthesizer(context=context_policy),
            input=ResearchPlan,
            output=BranchView,
            name="policy_branch",
        ),
        "economic": Sequential(
            ResearchFramer(context=context_economic),
            ReAct(config=cfg, context=context_economic),
            BranchSynthesizer(context=context_economic),
            input=ResearchPlan,
            output=BranchView,
            name="economic_branch",
        ),
    }

    parallel = Parallel(
        branches,
        input=ResearchPlan,
        output=_PerspectiveBundle,
        combine=_combine,
        name="perspective_parallel",
    )

    editor = Reasoner(
        config=cfg,
        input=_PerspectiveBundle,
        output=ResearchReport,
        role="You are the final editor synthesizing all perspectives.",
        task=(
            "Write one decisive headline and one concise reasoning paragraph "
            "that synthesizes all three branch views."
        ),
        rules=(
            "Headline is one sentence and commits to a position.",
            "Reasoning should integrate biology, policy, and economics.",
        ),
    )

    return Sequential(
        planner,
        parallel,
        editor,
        input=ResearchRequest,
        output=ResearchReport,
        name="research_analyst",
    )


# ---------------------------------------------------------------------------
# Pretty output.
# ---------------------------------------------------------------------------


def _print_report(report: ResearchReport) -> None:
    if not _RICH:
        print(f"headline:  {report.headline}")
        print(f"reasoning: {report.reasoning}")
        return
    tree = Tree(f"[bold green]headline[/]  {report.headline}")
    tree.add(f"[dim]reasoning[/]  {report.reasoning}")
    Console(width=120).print(tree)


# ---------------------------------------------------------------------------
# Main.
# ---------------------------------------------------------------------------


async def main(args: argparse.Namespace) -> None:
    if args.offline:
        print(
            f"[{_SCRIPT}] --offline: this example needs a real LLM; "
            "exiting 0 as no-op."
        )
        return

    attached = False
    if args.dashboard is not None:
        attached = attach_dashboard(
            args.dashboard,
            open_browser=not args.no_open,
            default=DEFAULT_DASHBOARD,
        )

    cfg = local_config(
        sampling=Sampling(temperature=0.4, max_tokens=2048),
        resilience=Resilience(max_retries=2, backoff_base=0.5),
    )
    print(f"[{_SCRIPT}] backend={cfg.backend} host={cfg.host} model={cfg.model}")
    if not server_reachable(cfg.host or ""):
        print(f"[{_SCRIPT}] cannot reach {cfg.host} — start llama-server", file=sys.stderr)
        raise SystemExit(1)

    print_rule("Stage 1 — assemble workflow")
    agent = assemble(cfg=cfg)
    print_panel(
        "Pre-build identity",
        (
            f"name: {agent.name}\n"
            f"hash_content: {agent.hash_content}\n"
            f"summary:\n{agent.summary()}"
        ),
    )

    # abuild() compiles the graph and checks every typed handoff.
    print_rule("Stage 2 — abuild() + validate()")
    await agent.abuild()
    request = ResearchRequest(
        question=args.question,
        audience="a thoughtful general reader",
    )
    # validate() confirms this runtime payload matches the built input contract.
    agent.validate(request)
    print_panel("Validation", "request validated successfully against built input schema")

    print_rule("Stage 3 — graph + prompt introspection")
    print_panel("Graph outline", agent.graph_outline())
    print_panel("Mermaid", agent.graph_mermaid())
    graph_json = agent.graph_json()
    print_panel(
        "Graph JSON summary",
        (
            f"root: {graph_json['root']}\n"
            f"nodes: {len(graph_json['nodes'])}\n"
            f"edges: {len(graph_json['edges'])}"
        ),
    )

    # __rich__ is exercised when rich is available; summary() is the plain fallback.
    if _RICH:
        Console(width=120).print(agent)
    else:
        print(agent.summary())

    print_rule("Stage 4 — invoke")
    print_panel(
        "Input",
        f"question: {request.question}\naudience: {request.audience}",
    )
    out = await agent(request)

    print_rule("Stage 5 — final report + envelope")
    _print_report(out.response)
    print_panel(
        "Envelope (reproducibility fingerprint)",
        (
            f"run_id:             {out.run_id}\n"
            f"agent_path:         {out.agent_path}\n"
            f"latency_ms:         {out.latency_ms:.1f}\n"
            f"hash_input:         {out.hash_input}\n"
            f"hash_graph:         {out.hash_graph}\n"
            f"hash_prompt:        {out.hash_prompt}\n"
            f"hash_output_schema: {out.hash_output_schema}\n"
            f"agent.hash_content: {agent.hash_content}"
        ),
    )

    if attached:
        host, port = parse_dashboard_target(args.dashboard, default=DEFAULT_DASHBOARD)
        print(
            f"[dashboard] still live at http://{host}:{port}  "
            "(ctrl+c the dashboard server to stop)"
        )


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--offline",
        action="store_true",
        help="No-op for verify.sh; this example needs a real LLM to run.",
    )
    p.add_argument(
        "--question",
        default="Why are honeybee colonies collapsing in temperate regions?",
        help="The research question to feed the workflow.",
    )
    p.add_argument(
        "--dashboard",
        nargs="?",
        const=DEFAULT_DASHBOARD,
        default=None,
        metavar="HOST:PORT",
        help="Attach to a running operad-dashboard server (default 127.0.0.1:7860).",
    )
    p.add_argument(
        "--no-open",
        action="store_true",
        help="Do not open the browser when --dashboard attaches.",
    )
    return p.parse_args()


if __name__ == "__main__":
    asyncio.run(main(_parse_args()))
