"""Textual backpropagation internals."""

from __future__ import annotations

from operad.optim.backprop.backward import SplitRule, backward, register_backward_rule
from operad.optim.backprop.grad import (
    PARAMETER_GRAD_AGENTS,
    BackpropAgent,
    CategoricalParameterGrad,
    ExampleListParameterGrad,
    FloatParameterGrad,
    ParameterGradAgent,
    ParameterGradInput,
    ParameterGradOutput,
    PropagateInput,
    PropagateOutput,
    RuleListParameterGrad,
    TextParameterGrad,
    parameter_grad,
    parameter_grad_for,
    propagate,
)
from operad.optim.backprop.rewrite import (
    REWRITE_AGENTS,
    CategoricalRewriter,
    ConfigurationRewriter,
    ExampleListRewriter,
    FloatRewriter,
    RewriteAgent,
    RewriteRequest,
    RewriteResponse,
    RuleListRewriter,
    TextRewriter,
    apply_rewrite,
    rewriter_for,
)
from operad.optim.backprop.tape import Tape, TapeEntry, TapeObserver, enabled, tape
from operad.optim.backprop.traceback import PromptTraceback, TracebackFrame, traceback

__all__ = [
    "PARAMETER_GRAD_AGENTS",
    "REWRITE_AGENTS",
    "BackpropAgent",
    "CategoricalParameterGrad",
    "CategoricalRewriter",
    "ConfigurationRewriter",
    "ExampleListParameterGrad",
    "ExampleListRewriter",
    "FloatParameterGrad",
    "FloatRewriter",
    "ParameterGradAgent",
    "ParameterGradInput",
    "ParameterGradOutput",
    "PromptTraceback",
    "PropagateInput",
    "PropagateOutput",
    "RewriteAgent",
    "RewriteRequest",
    "RewriteResponse",
    "RuleListParameterGrad",
    "RuleListRewriter",
    "SplitRule",
    "Tape",
    "TapeEntry",
    "TapeObserver",
    "TextParameterGrad",
    "TextRewriter",
    "TracebackFrame",
    "apply_rewrite",
    "backward",
    "enabled",
    "parameter_grad",
    "parameter_grad_for",
    "propagate",
    "register_backward_rule",
    "rewriter_for",
    "tape",
    "traceback",
]
