"""operad: a typed, composable agent library built on top of strands."""

from __future__ import annotations

from .agents import (
    Action,
    Actor,
    Answer,
    Choice,
    Classifier,
    Critic,
    Evaluator,
    Extractor,
    Hit,
    Hits,
    Observation,
    Parallel,
    Pipeline,
    Planner,
    Query,
    ReAct,
    Reasoner,
    Reflection,
    ReflectionInput,
    Reflector,
    Retriever,
    RouteInput,
    Router,
    Switch,
    Task,
    Thought,
    Tool,
    ToolCall,
    ToolResult,
    ToolUser,
)
from .algorithms import BestOfN, Candidate, Score
from .core import (
    Agent,
    AgentGraph,
    AgentState,
    Backend,
    Configuration,
    Edge,
    Example,
    Node,
    abuild_agent,
    build_agent,
    to_json,
    to_mermaid,
)
from .metrics import ExactMatch, JsonValid, Latency, Metric
from .models import resolve_model
from .runtime import SlotRegistry, set_limit
from .utils.errors import BuildError, BuildReason

__all__ = [
    "Action",
    "Actor",
    "Agent",
    "AgentGraph",
    "AgentState",
    "Answer",
    "Backend",
    "BestOfN",
    "BuildError",
    "BuildReason",
    "Candidate",
    "Choice",
    "Classifier",
    "Configuration",
    "Critic",
    "Edge",
    "Evaluator",
    "ExactMatch",
    "Example",
    "Extractor",
    "Hit",
    "Hits",
    "JsonValid",
    "Latency",
    "Metric",
    "Node",
    "Observation",
    "Parallel",
    "Pipeline",
    "Planner",
    "Query",
    "ReAct",
    "Reasoner",
    "Reflection",
    "ReflectionInput",
    "Reflector",
    "Retriever",
    "RouteInput",
    "Router",
    "Score",
    "SlotRegistry",
    "Switch",
    "Task",
    "Thought",
    "Tool",
    "ToolCall",
    "ToolResult",
    "ToolUser",
    "abuild_agent",
    "build_agent",
    "resolve_model",
    "set_limit",
    "to_json",
    "to_mermaid",
]
