"""operad: a typed, composable agent library built on top of strands."""

from __future__ import annotations

from .agents import (
    Action,
    Actor,
    Answer,
    Classifier,
    Critic,
    Evaluator,
    Extractor,
    Observation,
    Parallel,
    Pipeline,
    Planner,
    ReAct,
    Reasoner,
    Task,
    Thought,
)
from .algorithms import BestOfN, Candidate, Score
from .core import (
    Agent,
    AgentGraph,
    AgentState,
    Backend,
    Configuration,
    Edge,
    Example,
    Node,
    abuild_agent,
    build_agent,
    to_json,
    to_mermaid,
)
from .eval import EvalReport, evaluate
from .metrics import (
    Contains,
    CostTracker,
    ExactMatch,
    JsonValid,
    Latency,
    Metric,
    RegexMatch,
    Rouge1,
    RubricCritic,
)
from .models import resolve_model
from .runtime import SlotRegistry, set_limit
from .utils.errors import BuildError, BuildReason

__all__ = [
    "Action",
    "Actor",
    "Agent",
    "AgentGraph",
    "AgentState",
    "Answer",
    "Backend",
    "BestOfN",
    "BuildError",
    "BuildReason",
    "Candidate",
    "Classifier",
    "Configuration",
    "Contains",
    "CostTracker",
    "Critic",
    "Edge",
    "EvalReport",
    "Evaluator",
    "ExactMatch",
    "Example",
    "Extractor",
    "JsonValid",
    "Latency",
    "Metric",
    "Node",
    "Observation",
    "Parallel",
    "Pipeline",
    "Planner",
    "ReAct",
    "Reasoner",
    "RegexMatch",
    "Rouge1",
    "RubricCritic",
    "Score",
    "SlotRegistry",
    "Task",
    "Thought",
    "abuild_agent",
    "build_agent",
    "evaluate",
    "resolve_model",
    "set_limit",
    "to_json",
    "to_mermaid",
]
